GET http://lukasedv-phonebook-backend.azurewebsites.net/api/persons

###
GET http://localhost:3000/api/persons

###

GET http://lukasedv-phonebook-backend.azurewebsites.net/api/persons/1

###
DELETE http://localhost:3001/api/persons/axxz2jp00

###
POST https://lukasedv-phonebook-backend.azurewebsites.net/api/persons
content-type: application/json

{
    "name": "Lukas Lundin",
    "number": "333123123123"
}

###
PUT https://lukasedv-phonebook-backend.azurewebsites.net/api/persons/60ec8bb26c8501002eb8de5c
content-type: application/json

{
    "name": "Lukas Lundin",
    "number": "333123123123"
}

###

POST http://localhost:3000/api/persons
content-type: application/json

{
    "name": "Puppe",
    "number": "000-002"
}